# Generated by Django 5.0.6 on 2024-07-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='pedido',
            field=models.BooleanField(default=True),
        ),
    ]
