# Generated by Django 5.0.7 on 2024-08-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('nickyname', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField()),
                ('is_activatedf', models.BooleanField(default=True)),
            ],
        ),
    ]
