# Generated by Django 5.0.7 on 2024-08-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='is_activatedf',
        ),
        migrations.AddField(
            model_name='programmer',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
