# Generated by Django 5.0.7 on 2024-08-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_programmer_is_activatedf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='is_activated',
            field=models.BooleanField(default=True),
        ),
    ]
